//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalaUkladnica.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    /// <summary>
    ///  public partial class LOGI_MALAUKLADNICA_ACTION
    /// </summary>

    public partial class LOGI_MALAUKLADNICA_ACTION
    {  /// <summary>
       ///  public int LMUA_ID 
       /// </summary>

        [Key]
        public int LMUA_ID { get; set; }
      
        /// <summary>
        ///  public string LMUA_USERNAME 
        /// </summary>

        public string LMUA_USERNAME { get; set; }
      
        /// <summary>
        ///  public string LMUA_USERID 
        /// </summary>

        public string LMUA_USERID { get; set; }
      
        /// <summary>
        ///  public string LMUA_CONTAINER_NR 
        /// </summary>

        public string LMUA_CONTAINER_NR { get; set; }
       
        /// <summary>
        ///  public string LMUA_MESSAGE
        /// </summary>

        public string LMUA_MESSAGE { get; set; }

        /// <summary>
        /// public System.DateTime LMUA_CREATED_DATE 
        /// </summary>

        public System.DateTime LMUA_CREATED_DATE { get; set; }

        /// <summary>
        /// public string LMUA_ACTION_TYP
        /// </summary>
    
        public string LMUA_ACTION_TYPE { get; set; }
    }
}
