
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SmallStacker.Model
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LOGI_MALAUKLADNICA_ACTION
{

    [Key]
    public int LMUA_ID { get; set; }

    public string LMUA_USERNAME { get; set; }

    public string LMUA_USERID { get; set; }

    public string LMUA_CONTAINER_NR { get; set; }

    public string LMUA_MESSAGE { get; set; }

    public System.DateTime LMUA_CREATED_DATE { get; set; }

    public string LMUA_ACTION_TYPE { get; set; }

}

}
