//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmallStacker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmallStacker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видали контейнер з буфору.
        /// </summary>
        public static string ButtonDeleteContainerFromBufferStation {
            get {
                return ResourceManager.GetString("ButtonDeleteContainerFromBufferStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зніми контейнер.
        /// </summary>
        public static string ButtonDowloandContainer {
            get {
                return ResourceManager.GetString("ButtonDowloandContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Покажи історію.
        /// </summary>
        public static string ButtonDowloandHistory {
            get {
                return ResourceManager.GetString("ButtonDowloandHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Висвітли інформацію про контейнер.
        /// </summary>
        public static string ButtonGetContainerInfo {
            get {
                return ResourceManager.GetString("ButtonGetContainerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вишли контейнер.
        /// </summary>
        public static string ButtonSendContainerToTracker {
            get {
                return ResourceManager.GetString("ButtonSendContainerToTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контейнер пустий.
        /// </summary>
        public static string CheckBoxContainerIsEmpty {
            get {
                return ResourceManager.GetString("CheckBoxContainerIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не перевіряй контейнер в базі САП.
        /// </summary>
        public static string CheckBoxDontCheckContainerInSAP {
            get {
                return ResourceManager.GetString("CheckBoxDontCheckContainerInSAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дії виконані.
        /// </summary>
        public static string ContainerActionComplete {
            get {
                return ResourceManager.GetString("ContainerActionComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тара не існує.
        /// </summary>
        public static string ContainerDontExist {
            get {
                return ResourceManager.GetString("ContainerDontExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Порожні місця в SAP.
        /// </summary>
        public static string ContainerEmptyLocalizationInSAP {
            get {
                return ResourceManager.GetString("ContainerEmptyLocalizationInSAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інформація про контейнер.
        /// </summary>
        public static string ContainerInformation {
            get {
                return ResourceManager.GetString("ContainerInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не візьміть -&gt; є замовлення на випуск.
        /// </summary>
        public static string ContainerSpendOrder {
            get {
                return ResourceManager.GetString("ContainerSpendOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контейнер.
        /// </summary>
        public static string DataGridTextColumnHeaderContainer {
            get {
                return ResourceManager.GetString("DataGridTextColumnHeaderContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата/Час.
        /// </summary>
        public static string DataGridTextColumnHeaderDataTime {
            get {
                return ResourceManager.GetString("DataGridTextColumnHeaderDataTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повідомлення.
        /// </summary>
        public static string DataGridTextColumnHeaderMessage {
            get {
                return ResourceManager.GetString("DataGridTextColumnHeaderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відповідь.
        /// </summary>
        public static string DataGridTextColumnHeaderResponse {
            get {
                return ResourceManager.GetString("DataGridTextColumnHeaderResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Користувач.
        /// </summary>
        public static string DataGridTextColumnHeaderUser {
            get {
                return ResourceManager.GetString("DataGridTextColumnHeaderUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole nie może być puste!.
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завантаження контейнера.
        /// </summary>
        public static string GetContainer {
            get {
                return ResourceManager.GetString("GetContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видалення контейнера з буфера станції.
        /// </summary>
        public static string GetContainerFromBufferStation {
            get {
                return ResourceManager.GetString("GetContainerFromBufferStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ukraina.
        /// </summary>
        public static string GetInfoRes {
            get {
                return ResourceManager.GetString("GetInfoRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Історія контейнера.
        /// </summary>
        public static string HeaderContainerHistory {
            get {
                return ResourceManager.GetString("HeaderContainerHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операціі на контейнері.
        /// </summary>
        public static string HeaderContainerOperation {
            get {
                return ResourceManager.GetString("HeaderContainerOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контейнер №.
        /// </summary>
        public static string LabelContainerNumber {
            get {
                return ResourceManager.GetString("LabelContainerNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата від.
        /// </summary>
        public static string LabelDataFrom {
            get {
                return ResourceManager.GetString("LabelDataFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to До.
        /// </summary>
        public static string LabelDataTo {
            get {
                return ResourceManager.GetString("LabelDataTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ціль .
        /// </summary>
        public static string LabelDestinationForController {
            get {
                return ResourceManager.GetString("LabelDestinationForController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показник АБС.
        /// </summary>
        public static string LabelPointerABC {
            get {
                return ResourceManager.GetString("LabelPointerABC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пріоритет.
        /// </summary>
        public static string LabelPriority {
            get {
                return ResourceManager.GetString("LabelPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Немає дозволів.
        /// </summary>
        public static string NoPermission {
            get {
                return ResourceManager.GetString("NoPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        public static string RadioButtonA {
            get {
                return ResourceManager.GetString("RadioButtonA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Б.
        /// </summary>
        public static string RadioButtonB {
            get {
                return ResourceManager.GetString("RadioButtonB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        public static string RadioButtonC {
            get {
                return ResourceManager.GetString("RadioButtonC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відправка контейнера в штабелер.
        /// </summary>
        public static string SendContainer {
            get {
                return ResourceManager.GetString("SendContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wysłanie kontenera na układnicę 666 po ukrainsku.
        /// </summary>
        public static string SendContainterMessage {
            get {
                return ResourceManager.GetString("SendContainterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка зв&apos;язку з сервером штабелерів.
        /// </summary>
        public static string ServerComunnicationError {
            get {
                return ResourceManager.GetString("ServerComunnicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мала укладальниця.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невідоме повідомлення про помилку.
        /// </summary>
        public static string UnknownMessage {
            get {
                return ResourceManager.GetString("UnknownMessage", resourceCulture);
            }
        }
    }
}
